version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    restart: always
  back:
    build: .
    command: npm run serve
    depends_on:
      - mongo
    env_file:
      - ./env/dev.env
    ports:
      - 3000:3000
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./src:/app/src
